In [1]:
!pip install torch

In [2]:
import torch
print(torch.__version__)

2.4.1+cu121


In [5]:
# Example with 1-D data
data = [1.0, 2.0, 3.0]
tensor = torch.Tensor(data)
print("Example with 1-D data")
print(tensor)

# Example with 2-D data
data = [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
tensor = torch.Tensor(data)
print("\nExample with 2-D data")
print(tensor)

# Example with 3-D data
data = [[[1, 2], [3, 4]],
        [[5, 6], [7, 8]]]
tensor = torch.Tensor(data)
print("\nExample with 3-D data")
print(tensor)

Example with 1-D data
tensor([1., 2., 3.])

Example with 2-D data
tensor([[1., 2., 3.],
        [4., 5., 6.]])

Example with 3-D data
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [6]:
# Initialize an empty Tensor
# Construct a 2x3 matrix, uninitialized
x = torch.empty(2, 3)
print(x)

tensor([[ 1.0451e-32,  4.3258e-41, -3.4524e-10],
        [ 3.2198e-41,  4.4842e-44,  0.0000e+00]])


In [8]:
# Randomly initialized Tensor
x = torch.rand(2, 3)
print(x)

tensor([[0.0771, 0.0828, 0.9955],
        [0.2489, 0.1575, 0.9289]])


In [10]:
# Tensor with zeros or ones
x = torch.zeros(2, 3)
print("Matrix of zeros")
print(x)

# Create a matrix of all zeros and explicitly set data type to be long int
x = torch.zeros(2, 3, dtype=torch.long)
print("\nMatrix of zeros typecasted to long")
print(x)

x = torch.ones(2, 3, dtype=torch.long)
print("\nMatrix of ones typecasted to long")
print(x)

Matrix of zeros
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Matrix of zeros typecasted to long
tensor([[0, 0, 0],
        [0, 0, 0]])

Matrix of ones typecasted to long
tensor([[1, 1, 1],
        [1, 1, 1]])


### Size of a Tensor

In [11]:
# Create Tensor based on existing Tensor
x = x.new_ones(2, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.7845, -0.2151, -1.0789],
        [ 0.5597,  1.2260, -1.0147]])


In [13]:
# Example with  1-D data
data = [1.0, 2.0, 3.0]
tensor = torch.Tensor(data)
print("Example with 1-D data")
print(tensor)
print(tensor.size())

# Example with 2-D data
data = [[1.0, 2.0, 3.0], [4, 5, 6]]
tensor = torch.Tensor(data)
print("\nExample with 2-D data")
print(tensor)
print(tensor.size())

# Example with 3-D data
data = [[[1, 2], [3, 4]],
        [[5, 6], [7, 8]]]
tensor = torch.Tensor(data)
print("\nExample with 3-D data")
print(tensor)
print(tensor.size())


Example with 1-D data
tensor([1., 2., 3.])
torch.Size([3])

Example with 2-D data
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])

Example with 3-D data
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
torch.Size([2, 2, 2])


#### Numpy vs PyTorch code for 5 operations

In [9]:
# PyTorch
import torch
tensor = torch.tensor([1, 2, 3])
result_tensor = tensor + 5
print(result_tensor)

# Numpy
import numpy as np
array = np.array([1, 2, 3])
result_array = array + 5
print(result_array)

tensor([6, 7, 8])
[6 7 8]


In [10]:
# Addition
x = torch.Tensor([1, 2, 3])
y = torch.Tensor([4, 5, 6])

z = x + y
print(z)

# Using method
print(torch.add(x ,y))

tensor([5., 7., 9.])
tensor([5., 7., 9.])


Any operation that mutates a tensor in place is post-fixed with an underscore. For example, x.copy_(y), x.t_() will change x

### Reshaping Tensors

In [11]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 2) # the size -1 is used as a placeholder and is inferred from other dimensions
print(x.size())
print(y.size())
print(z.size())

torch.Size([4, 4])
torch.Size([16])
torch.Size([8, 2])


In [12]:
x = torch.randn(1)
print(x)         #1D tensor with one element
print(x.item())  #This method is used to convert a 1 element tensor into a Python native float or integer.

tensor([-0.1020])
-0.10203853994607925


### Converting to and from Numpy

In [13]:
a = torch.ones(5)
print("Original a:", a)

b = a.numpy()
print("Original b:", b)

a.add_(1)
print("New a:", a)
print("New b:", b)

Original a: tensor([1., 1., 1., 1., 1.])
Original b: [1. 1. 1. 1. 1.]
New a: tensor([2., 2., 2., 2., 2.])
New b: [2. 2. 2. 2. 2.]


In [14]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


####CUDA Tensors: Enable GPU on your Colab notebook
Go to Edit -> Notebook Settings -> select GPU as Hardware accelerator

In [1]:
import torch
print(torch.cuda.is_available())
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device('cuda')             # a CUDA device object
    x = torch.Tensor([1, 2, 3])
    y = torch.ones_like(x, device=device)     # directly create a tensor on GPU
    x = x.to(device)                          # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))          # ``.to`` can also change dtype together!

True
tensor([2., 3., 4.], device='cuda:0')
tensor([2., 3., 4.], dtype=torch.float64)


### Autograd: Automatic Differentiation

The autograd package provides automatic differentiation for all operations on Tensors. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

torch.Tensor is the central class of the package. If you set its attribute .requires_grad as True, it starts to track all operations on it. When you finish your computation you can call .backward() and have all the gradients computed automatically. The gradient for this tensor will be accumulated into .grad attribute.

To stop a tensor from tracking history, you can call .detach() to detach it from the computation history, and to prevent future computation from being tracked.

To prevent tracking history (and using memory), you can also wrap the code block in with torch.no_grad():. This can be particularly helpful when evaluating a model because the model may have trainable parameters with requires_grad=True, but for which we don't need the gradients.

In [2]:
import torch
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y = x + 2
print(y)
# y was created as a result of an operation, so it has a grad_fn.

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


.requires_grad_( ... ) changes an existing Tensor's requires_grad flag in-place. The input flag defaults to False if not given.

In [5]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)

a.requires_grad_(True)
print(a.requires_grad)

False
True


Let us consider a complete example now.

Let $out = \frac{1}{4}\sum_i z_i$,  
$z_i = 3(x_i+2)^2$  
and $z_i\bigr\rvert_{x_i=1} = 27$.  
Therefore,  
$\frac{\partial out}{\partial x_i} = \frac{1}{4}\frac{\partial z_i}{\partial x_i} = \frac{1}{4}.3.2(x_i+2) = \frac{3}{2}(x_i+2)$,  
 hence  
$\frac{\partial out}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{9}{2} = 4.5$



In [6]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * y * 3
out = z.mean()

out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


You can also stop autograd from tracking history on Tensors with .requires_grad=True either by wrapping the code block in with torch.no_grad():

In [7]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
